### ISSUE TITLE
Scrollbar don't work sometimes and Smear somethings show

### ISSUE THREAD

**Issue by void285** [AHK-just-me/Class_LV_Colors#1]
Hello, I find sometimes lv don't scroll anymore, though the scrollbar can scroll. If you run the sample, and scroll up and down quickly, it will be very likely reproduced.
There is a related problem, I'm not sure how to describe it, maybe it should be called Smear. It's like this, content of colum 2 show in column 1, and part content of column 1 stays there, grids dont's align anymore.
![image](https://user-images.githubusercontent.com/612912/126890845-dd3479b4-2d3c-4abb-b318-0ab4c3785996.png)

**Comment by Chutriel235** [comment]
I have the same issue. Also the smear problem. Until now is wasnt able to find a way to fix it.

**Comment by AHK-just-me** [comment]
That's a known issue caused by the AHK message handling.

**Comment by Chutriel235** [comment]
If you dont use AltSubmit and use the critical function in the Class you can solve the problem.
